server:
  port: 8045
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ExamManager?setUnicode=true&characterEncoding=utf8
    username: root
    password: abckeke123
logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
        web: ERROR
      hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG
front_side:
  host: localhost
  port: 8045
